import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import axios from "axios";
import Cover from "@/components/cover/Cover";
import { useRouter } from "next/router";
import Pagination from "@/components/pagination/Pagination";
import PageBody from "@/components/pagebody/PageBody";
import Footer from "@/components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ adverts, query, perPage, count }) {
  const router = useRouter();

  function setCurrentPage(page) {
    console.log("handling current page", page);
    router.push({
      query: { page: page },
    });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Cover />
        <PageBody adverts={adverts} />
        {count > 0 && (
          <Pagination
            // className={styles.paginationBar}
            currentPage={parseInt(router?.query?.page)}
            totalCount={count}
            pageSize={perPage}
            onPageChange={(page) => setCurrentPage(page)}
          />
        )}
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps({ query }) {
  console.log(new URLSearchParams(query).toString());
  const queryString = new URLSearchParams(query).toString();
  const res = await axios.get(
    `${process.env.NEXT_PUBLIC_REACT_BE_API}/adverts-room/search?${queryString}`
  );
  const { adverts, count, perPage } = res.data;
  console.log("map adv", count, adverts);
  return {
    props: {
      adverts,
      count,
      perPage,
    },
  };
}
