import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import axios from "axios";
import Cover from "@/components/cover/Cover";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ count }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Cover />
      </main>
    </>
  );
}

export async function getServerSideProps({ query }) {
  console.log(new URLSearchParams(query).toString());
  const queryString = new URLSearchParams(query).toString();
  const res = await axios.get(
    `${process.env.NEXT_PUBLIC_REACT_BE_API}/adverts-room/search?${queryString}`
  );
  const { adverts, count, perPage } = res.data;
  console.log("map adv", count, adverts);
  return {
    props: {
      adverts,
      count,
      perPage,
    },
  };
}
