export const SAVE_ADVERTS = "SAVE_ADVERTS";
export const SAVE_ADVERT_BADGE = "SAVE_ADVERT_BADGE";
export const DELETETE_ADVERT_IMAGE = "DELETETE_ADVERT_IMAGE";
export const DELETE_ADVERT = "DELETE_ADVERT";
export const UPDATE_ADVERT = "UPDATE_ADVERT";
export const ADD_ADVERT = "ADD_ADVERT";
